% Generated by MATLAB(R) 25.2 (R2025b) and Satellite Communications Toolbox 25.2 (R2025b).
% Generated on: 06-Jun-2026 00:19:35
clc, clearvars, close all;
%% Generating DVB-S2 waveform

% ldpc encoder
% Download LDPC parity matrices if not available
if ~exist('dvbs2xLDPCParityMatrices.mat','file')
    if ~exist('s2xLDPCParityMatrices.zip','file')
        url = 'https://ssd.mathworks.com/supportfiles/spc/satcom/DVB/s2xLDPCParityMatrices.zip';
        websave('s2xLDPCParityMatrices.zip', url);
        unzip('s2xLDPCParityMatrices.zip');
    end
    addpath('s2xLDPCParityMatrices');
end

snr = 5;

% DVB-S2 configuration
wavegen = dvbs2WaveformGenerator;
wavegen.StreamFormat = "TS";
wavegen.NumInputStreams = 1;
wavegen.FECFrame = "normal";
wavegen.MODCOD = 8;
wavegen.DFL = getDFL(wavegen.MODCOD,wavegen.FECFrame);
wavegen.HasPilots = 1;
wavegen.RolloffFactor = 0.35;
wavegen.FilterSpanInSymbols = 10;
wavegen.SamplesPerSymbol = 2;
% input bit source:
NumPLFrames = 1;

% The PNSequence is commented out, and we no longer need 'pn = zeros(...)' 
% since we will generate the zeros directly inside the loop.
% pn = comm.PNSequence('Polynomial', 'x9+x5+1', ...);

if strcmp(wavegen.StreamFormat,"TS")
    syncBits = [0;1;0;0;0;1;1;1];
    pktLen = 1496;
    data =  cell(1, wavegen.NumInputStreams);
    for i = 1:wavegen.NumInputStreams
        numPkts = wavegen.MinNumPackets(i)*NumPLFrames;
        
        % Generate a column vector of pure zeros for the payload
        rawpkts = zeros(pktLen * numPkts, 1);
        
        txRawPkts = reshape(rawpkts, pktLen, numPkts);
        txPkts = [repmat(syncBits, 1, numPkts); txRawPkts];
        data{i} = txPkts(:);
    end

elseif strcmp(wavegen.StreamFormat,"GS") && any(wavegen.UPL>0)
    syncBits = [0;0;0;0;0;0;0;0];
    data =  cell(1, wavegen.NumInputStreams);
    for i = 1:wavegen.NumInputStreams
        numPkts = wavegen.MinNumPackets(i)*NumPLFrames;
        reset(pn);
        if length(wavegen.UPL) == 1
            pktLen = wavegen.UPL-8;
        else
            pktLen = wavegen.UPL(i)-8;
        end
        rawpkts = pn(pktLen * numPkts);
        txRawPkts = reshape(rawpkts, pktLen, numPkts);
        txPkts = [repmat(syncBits, 1, numPkts); txRawPkts];
        data{i} = txPkts(:);
    end
else
    data =  cell(1, wavegen.NumInputStreams);
    for i = 1:wavegen.NumInputStreams
        reset(pn);
        if length(wavegen.DFL) == 1
            rawpkts = pn(wavegen.DFL* NumPLFrames);
        else
            rawpkts = pn(wavegen.DFL(i)* NumPLFrames);
        end
        data{i} = rawpkts;
    end
end
in = data;

% Generation
txWaveform = [wavegen(in);flushFilter(wavegen)];

Fs = 1e+06; 								 % Specify the sample rate of the waveform in Hz

% Get MODCOD physical layer parameters
[modOrder, codeRate, cwLen] = satcom.internal.dvbs.getS2PHYParams(...
    wavegen.MODCOD, wavegen.FECFrame);

dataLen    = cwLen / log2(modOrder);   % number of data symbols per PLFRAME
slotLen    = 90;                       % symbols per slot
pilotBlkFreq = 16;                     % pilot inserted every 16 data slots
pilotSymLen  = 36;                     % symbols per pilot block

% Number of pilot blocks (Eq. from DVB-S2 standard)
numPilotBlks = floor(dataLen / (slotLen * pilotBlkFreq));
if floor(dataLen/(slotLen*16)) == dataLen/(slotLen*pilotBlkFreq)
    numPilotBlks = numPilotBlks - 1;
end

pilotLen  = numPilotBlks * pilotSymLen;
plFrameSize = dataLen + pilotLen + slotLen;   % total PL frame symbols
fprintf("\nPilot Length: %d \nPlFrame Size: %d\n ",pilotLen,plFrameSize)

% filtering the TX for reference (used in BER calculation)
txFilt = comm.RaisedCosineReceiveFilter(...
    'RolloffFactor',         wavegen.RolloffFactor, ...
    'FilterSpanInSymbols',   wavegen.FilterSpanInSymbols, ...
    'InputSamplesPerSymbol', wavegen.SamplesPerSymbol, ...
    'DecimationFactor',      wavegen.SamplesPerSymbol);
filterDelay = wavegen.FilterSpanInSymbols;
txSym_raw = txFilt(txWaveform);
txSymbols = txSym_raw(filterDelay+1:end);
release(txFilt);

% Pilot block positions within XFECFRAME
[~, pilotInd_raw] = satcom.internal.dvbs.pilotBlock(numPilotBlks);

% Add PLHEADER offset → positions within full PL frame
pilotInd  = pilotInd_raw + slotLen;   % slotLen = 90 = PLHEADER length

txPilots = txSymbols(pilotInd);

scatterplot(txPilots);

%% Impairments
% AWGN
A_p_dB = 15;
A_p_lin = 10^(-A_p_dB / 20);
phi     = 2 * pi * rand(1);
h_tilde = A_p_lin * exp(-1j * phi);
fadedWaveform = h_tilde*txWaveform;
rxWaveform = awgn(fadedWaveform,snr, 'measured');

rxFilter = comm.RaisedCosineReceiveFilter( ...
    'RolloffFactor',         wavegen.RolloffFactor, ...
    'FilterSpanInSymbols',   wavegen.FilterSpanInSymbols, ...
    'InputSamplesPerSymbol', wavegen.SamplesPerSymbol, ...
    'DecimationFactor',      wavegen.SamplesPerSymbol);

rxSym_raw   = rxFilter(rxWaveform);

rxSymbols   = rxSym_raw(filterDelay+1:end);
release(rxFilter);

rxPilots = rxSymbols(pilotInd);

scatterplot( rxPilots);


%% 

% Constellation Diagram
constel = comm.ConstellationDiagram('ColorFading', true, ...
    'ShowTrajectory', 0, ...
    'SamplesPerSymbol', 4, ...
    'ShowReferenceConstellation', false);
constel(rxWaveform);
release(constel);


%% helper function
function dfl = getDFL(modCod,fecFrame)
% Get data field length
    if strcmp(fecFrame,"normal")
        nDefVal = [16008 21408 25728 32208 38688 43040 48408 51648 53840 57472 ...
            58192 38688 43040 48408 53840 57472 58192 43040 48408 51648 53840 ...
            57472 58192 48408 51648 53840 57472 58192] - 80;
    else
        % MODCOD values 11, 17, 23, and 28 are not valid when you set the FECFrame property to "short"
        nDefVal = [3072 5232 6312 7032 9552 10632 11712 12432 13152 14232 0 ...
            9552 10632 11712 13152 14232 0 10632 11712 12432 13152 14232 0 11712 ...
            12432 13152 14232 0] - 80;
    end
    dfl = nDefVal(modCod);
end